FROM golang:latest as build
WORKDIR /app
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-w -s" -o servertwo ./server2/cmd/server

FROM alpine
WORKDIR /app
COPY --from=build /app/servertwo .
RUN apk add --no-cache ca-certificates
CMD ["./servertwo"]